# Use root/example as user/password credentials
version: '3.1'
services:
  db-simplon:
    image: mysql
    #    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin-simplon:
    image: phpmyadmin
    ports:
      - "8008:80"
    environment:
      - PMA_ARBITRARY=1