# Use root/example as user/password credentials
version: '3.8'
services:

  db-simplon:
    container_name: db-simplon
    image: mysql
    #    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    #volumes:
    #  - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      backend:
        ipv4_address: 10.5.0.5

  phpmyadmin-simplon:
    image: phpmyadmin
    ports:
      - "8008:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      backend:
        ipv4_address: 10.5.0.6

  flyway:
    image: boxfuse/flyway
    volumes:
      - ./flyway/src/main/resources/db/migration:/flyway/sql
    command: -url=jdbc:mysql://db-simplon:3306/mysql -schemas=simplon_ville -user=root -password=example migrate
    depends_on:
       db-simplon:
         condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
    #healthcheck:
    #  test: [ "CMD", "db-simplon" ,"ping", "-h", "localhost" ]
    #  timeout: 20s
    #  retries: 10
    networks:
      backend:
        ipv4_address: 10.5.0.8

  api:
    container_name: Application
    build :
      context: .
      dockerfile: api/Dockerfile
    image: api_simplon
    depends_on:
      flyway:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    networks:
      backend:
        ipv4_address: 10.5.0.7

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16